kind: helm-release
apiVersion: 1.0
build:
  context: ../../../../
  dockerfile: src/Services/Identity/Identity.API/Dockerfile
install:
  chart: ../../../../k8s/helm/identity-api
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  - ../../../../k8s/helm/inf.yaml
  - ../../../../k8s/helm/app.yaml
  set:
    replicaCount: 1
    image:
      tag: $(tag)
      pullPolicy: Never
    inf:
      k8s:
        dns: "$(spacePrefix)identity$(hostSuffix)"
    ingress:
      hosts:
      # This expands to [space.s.]identity.<guid>.<region>.aksapp.io
      - $(spacePrefix)identity(hostSuffix)
configurations:
  develop:
    build:
      dockerfile: Dockerfile.develop
      useGitIgnore: true
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION:-Debug}
    container:
      sync:
      - "**/Pages/**"
      - "**/Views/**"
      - "**/wwwroot/**"
      - "!**/*.{sln,csproj}"
      command: [dotnet, run, --no-restore, --no-build, --no-launch-profile, -c, "${BUILD_CONFIGURATION:-Debug}"]
      iterate:
        processesToKill: [dotnet, vsdbg]
        buildCommands:
        - [dotnet, build, --no-restore, -c, "${BUILD_CONFIGURATION:-Debug}"]
