replicaCount: 1
clusterName: eshop-aks
pathBase: /webshoppingapigw

image:
  repository: envoyproxy/envoy
  tag: v1.21.0

service:
  type: ClusterIP
  port: 80
  adminPort: 8001

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env: {}

envoy:
  configPath: /etc/envoy

probes:
  liveness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 15
    port: 8001
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 60
    port: 8001