apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.app.svc.zipkin }}
  labels:
    app: {{ template "zipkin.name" . }}
    chart: {{ template "zipkin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "zipkin.name" . }}
    release: {{ .Release.Name }}