kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: seq
  labels:
    app: eshop
    service: seq
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /seq(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: seq
            port:
              number: 80
