{{- if .Values.ingress.enabled -}}
{{- $ingressPath := include "pathBase" . -}}
{{- $serviceName := .Values.app.svc.webmarketingapigw -}}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "apigwwm.fullname" . }}
  labels:
    app: {{ template "apigwwm.name" . }}
    chart: {{ template "apigwwm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
        - {{ .Values.inf.k8s.dns }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: http
  {{- end }}
{{- end }}
