replicaCount: 1
clusterName: eshop-aks
pathBase: /basket-api

image:
  repository: eshop/basket.api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: ConnectionString
      key: basket__ConnectionString
    - name: EventBusConnection
      key: all__EventBusConnection
    - name: ApplicationInsights__InstrumentationKey
      key: all__InstrumentationKey
    - name: AzureServiceBusEnabled
      key: all__UseAzureServiceBus
    - name: IdentityUrl
      key: urls__IdentityUrl
    - name: UseLoadTest
      key: basket__EnableLoadTest
  # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: OrchestratorType
      value: 'K8S'
probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 10
    periodSeconds: 15
    port: 80
  readiness:
    path: /hc
    timeoutSeconds: 5
    initialDelaySeconds: 90
    periodSeconds: 60
    port: 80
