apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.svc.basket }}
  labels:
    app: {{ template "basket-api.name" . }}
    chart: {{ template "basket-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: {{ template "basket-api.name" . }}
    release: {{ .Release.Name }}
