apiVersion: v1
kind: ConfigMap
metadata:
  labels:
#    addonmanager.kubernetes.io/mode: Reconcile
    app: addon-http-application-routing-ingress-nginx
    kubernetes.io/cluster-service: "true"
  name: addon-http-application-routing-nginx-configuration
  namespace: kube-system
data:
  proxy-buffer-size: "128k"
  proxy-buffers: "4 256k"
