# This file contains extra annotations to make Linkerd work with ingress.
# ingress.mesh.annotations are inserted into ingress.annotations of the resource being generated, if mesh is deployed
#
# It is designed to work with NGINX ingress controller or the Http Application Routing
#
# Check https://linkerd.io/2/tasks/using-ingress/ for more info or other ingress controllers
#
# If using your custom file, use -ingressMeshAnnotationsFile parameter in deploy-all.ps1

ingress:
  mesh:
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
        proxy_hide_header l5d-remote-ip;
        proxy_hide_header l5d-server-id;