{{- if .Values.ingress.enabled -}}
{{- if .Values.inf.k8s.local -}}
{{- $ingressPath := include "pathBase" . -}}
{{- $serviceName := .Values.app.svc.mvc }}
{{- $name := include "webmvc.fullname" . -}} 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}-local
  labels:
    app: {{ template "webmvc.name" . }}
    chart: {{ template "webmvc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}    
{{- if .Values.inf.mesh.enabled }} 
{{- with .Values.ingress.mesh.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      - path: {{ $ingressPath }}
        pathType: Prefix
        backend:
          service:
            name: {{ $serviceName }}
            port:
              number: 80     
        
{{- end -}}
{{- end -}}