apiVersion: v1
kind: ConfigMap
metadata:
  name: externalcfg
  labels:
    app: eshop  
data:
# Basket.API entries
  BasketBus: CONNECTION_STRING (NAME OF RABBITMQ CONTAINER OR Endpoint=sb://XXXX in case of using Azure)
  BasketRedisConStr: REDIS CONNECTION STRING FOR BASKET
# Catalog.API entries
  CatalogBus: CONNECTION_STRING (NAME OF RABBITMQ CONTAINER OR Endpoint=sb://XXXX in case of using Azure)
  CatalogSqlDb: Catalog SQL SERVER CONNECTION STRING (Server=xxxx;Intial Catalog=yyy;....)
# Identity.API entries
  IdentitySqlDb: Identity SQL SERVER CONNECTION STRING (Server=xxxx;Intial Catalog=yyy;....)
# Locations.API entries
  LocationsBus: CONNECTION_STRING (NAME OF RABBITMQ CONTAINER OR Endpoint=sb://XXXX in case of using Azure)
  LocationsNoSqlDb: Locations MongoDb ConnectionString
  LocationsNoSqlDbName: Locations MongoDb database (LocationsDb)
# Marketing.API entries
  MarketingBus: CONNECTION_STRING (NAME OF RABBITMQ CONTAINER OR Endpoint=sb://XXXX in case of using Azure)
  MarketingNoSqlDb: Marketing MongoDb ConnectionString
  MarketingNoSqlDbName: Marketing MongoDb database (MarketingDb)
  MarketingSqlDb: Marketing SQL SERVER CONNECTION STRING (Server=xxxx;Intial Catalog=yyy;....)
# Ordering.API entries
  OrderingBus: CONNECTION_STRING (NAME OF RABBITMQ CONTAINER OR Endpoint=sb://XXXX in case of using Azure)
  OrderingSqlDb: Ordering SQL SERVER CONNECTION STRING (Server=xxxx;Intial Catalog=yyy;....)
# Payment.API entries
  PaymentBus: CONNECTION_STRING (NAME OF RABBITMQ CONTAINER OR Endpoint=sb://XXXX in case of using Azure)
# GracePeriodManager entries
  GracePeriodTime: "5"  # Grace period duration (time when you can cancel order) in minutes
  GracePeriodCheckUpdateTime: "60000"   # Interval time to check new Order status (in milliseconds)
  GracePeriodManagerBus: CONNECTION_STRING (NAME OF RABBITMQ CONTAINER OR Endpoint=sb://XXXX in case of using Azure)
# Global entries
  UseAzureServiceBus: "TRUE" IF USE AZURE SB ("FALSE" FOR USING RABBITMQ)
  keystore: REDIS CONNECTION STRING FOR KEYSTORE