replicaCount: 1
clusterName: eshop-aks
pathBase: /ordering-signalrhub

image:
  repository: eshop/ordering.signalrhub
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - chart-example.local
  tls: []

cfg:
  checkUpdateTime: "15000"
  gracePeriodTime: "1"

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: ApplicationInsights__InstrumentationKey
      key: all__InstrumentationKey
    - name: EventBusConnection
      key: all__EventBusConnection
    - name: AzureServiceBusEnabled
      key: all__UseAzureServiceBus
    - name: IdentityUrl
      key: urls__IdentityUrl
    - name: SignalrStoreConnectionString
      key: signalr__StoreConnectionString
      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: OrchestratorType
      value: 'K8S'
    - name: IsClusterEnv
      values: 'True'

