replicaCount: 1
clusterName: eshop-aks
pathBase: /identity

image:
  repository: eshop/identity.api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - chart-example.local
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

env:
  urls:
  configmap:
    - name: ConnectionString
      key: identity__ConnectionString
    - name: DPConnectionString
      key: identity__keystore
    - name: ApplicationInsights__InstrumentationKey
      key: all__InstrumentationKey
    - name: MvcClient
      key: mvc_e
    - name: SpaClient
      key: spa_e
    - name: LocationApiClient
      key: locations_e
    - name: MarketingApiClient
      key: marketing_e
    - name: BasketApiClient
      key: basket_e
    - name: OrderingApiClient
      key: ordering_e
    - name: MobileShoppingAggClient
      key: mobileshoppingagg_e
    - name: WebShoppingAggClient
      key: webshoppingagg_e
    - name: XamarinCallback
      key: xamarin_callback_e
    - name: WebhooksApiClient
      key: webhooksapi_e
    - name: WebhooksWebClient
      key: webhooksweb_e
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: OrchestratorType
      value: 'K8S'
    - name: IsClusterEnv
      value: 'True'
probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 10
    periodSeconds: 15
    port: 80
  readiness:
    path: /hc
    timeoutSeconds: 5
    initialDelaySeconds: 90
    periodSeconds: 60
    port: 80