{{- if .Values.ingress.enabled -}}
{{- if .Values.inf.mesh.istio -}}
{{- $ingressPath := include "pathBase" . -}}
{{- $serviceName := $.Values.app.svc.webhooksweb -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "webhooks-web.fullname" . }}
  labels:
    app: {{ template "webhooks-web.name" . }}
    chart: {{ template "webhooks-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if and .Values.inf.tls.enabled .Values.inf.tls.issuer }}
  annotations:
    cert-manager.io/issuer: {{ .Values.inf.tls.issuer }}
{{- end }}
{{- if .Values.inf.mesh.istio }}
{{- with .Values.ingress.mesh.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
spec:
  hosts:
  {{- range .Values.ingress.hosts }}
  - {{ . }}
  {{- end }}
  gateways:
  {{- range .Values.ingress.gateways }}
  - {{ . }}
  {{- end }}
  http:
  {{- range .Values.ingress.hosts }}
  - route:
    - destination:
        host: {{ $serviceName }}
        port:
          number: 80
    match:
    - uri:
        prefix: {{ $ingressPath }}
  {{- end }}
{{- end }}
{{- end }}
