replicaCount: 1
clusterName: eshop-aks
pathBase: /webshoppingagg

image:
  repository: eshop/webshoppingagg
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  grpcPort: 81

ingress:
  enabled: false
  annotations: {}
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: ApplicationInsights__InstrumentationKey
      key: all__InstrumentationKey
    - name: urls__basket
      key: internalurls__basket
    - name: urls__catalog
      key: internalurls__catalog
    - name: urls__orders
      key: internalurls__ordering
    - name: urls__identity
      key: internalurls__identity
    - name: CatalogUrlHC
      key: internalurls__catalog__hc
    - name: BasketUrlHC
      key: internalurls__basket__hc
    - name: IdentityUrlHC
      key: internalurls__identity__hc
    - name: OrderingUrlHC
      key: internalurls__ordering__hc
    - name: MarketingUrlHC
      key: internalurls__marketing__hc
    - name: PaymentUrlHC
      key: internalurls__payment__hc
    - name: LocationUrlHC
      key: internalurls__location__hc
    - name: urls__grpcBasket
      key: internalurls__grpcBasket
    - name: urls__grpcCatalog
      key: internalurls__grpcCatalog
    - name: urls__grpcOrdering
      key: internalurls__grpcOrdering

      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: ASPNETCORE_URLS
      value: http://0.0.0.0:80
    - name: OrchestratorType
      value: 'K8S'
    - name: IsClusterEnv
      value: 'True'
probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 10
    periodSeconds: 15
    port: 80
  readiness:
    path: /hc
    timeoutSeconds: 5
    initialDelaySeconds: 90
    periodSeconds: 60      
    port: 80

