apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: null
  name: basket-api.default.svc.cluster.local
  namespace: default
spec:
  routes:
  - condition:
      method: GET
      pathRegex: /basket-api/api/v1/basket/[^/]*
    name: GET Basket {id}
    isRetryable: true
  - condition:
      method: GET
      pathRegex: /hc
    name: GET /hc
    isRetryable: false
  - condition:
      method: GET
      pathRegex: /liveness
    name: GET /liveness
    isRetryable: false
  - condition:
      method: POST
      pathRegex: /BasketApi\.Basket/GetBasketById
    name: POST /BasketApi.Basket/GetBasketById
    isRetryable: true
  - condition:
      method: POST
      pathRegex: /BasketApi\.Basket/UpdateBasket
    name: POST /BasketApi.Basket/UpdateBasket
    isRetryable: true
  - condition:
      method: POST
      pathRegex: /basket-api/api/v1/basket/checkout
    name: POST /v1/basket/checkout
    isRetryable: true
  retryBudget:
    retryRatio: 0.2
    minRetriesPerSecond: 10
    ttl: 10s