apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: null
  name: catalog-api.default.svc.cluster.local
  namespace: default
spec:
  routes:
  - condition:
      method: GET
      pathRegex: /catalog-api/api/v1/catalog/catalogbrands
    name: GET /v1/catalog/catalogbrands
    isRetryable: true
  - condition:
      method: GET
      pathRegex: /catalog-api/api/v1/catalog/catalogtypes
    name: GET /v1/catalog/catalogtypes
    isRetryable: true
  - condition:
      method: GET
      pathRegex: /catalog-api/api/v1/catalog/items
    name: GET /v1/catalog/items
    isRetryable: true
  - condition:
      method: GET
      pathRegex: /api/v1/catalog/items/[^/]*/pic/
    name: GET /v1/catalog/items/{id}/pic/
    isRetryable: false
  - condition:
      method: GET
      pathRegex: /hc
    name: GET /hc
    isRetryable: false
  - condition:
      method: GET
      pathRegex: /liveness
    isRetryable: false
    name: GET /liveness
  - condition:
      method: POST
      pathRegex: /CatalogApi\.Catalog/GetItemsByIds
    name: POST /CatalogApi.Catalog/GetItemsByIds
    isRetryable: true
  retryBudget:
    retryRatio: 0.2
    minRetriesPerSecond: 10
    ttl: 10s