replicaCount: 1
clusterName: eshop-aks
pathBase: /webstatus

image:
  repository: eshop/webstatus
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: ApplicationInsights__InstrumentationKey
      key: all__InstrumentationKey
    - name: BasketUrl
      key: internalurls__basket__hc
    - name: CatalogUrl
      key: internalurls__catalog__hc
    - name: IdentityUrl
      key: internalurls__identity__hc
    - name: OrderingUrl
      key: internalurls__ordering__hc      
    - name: OrderingBackgroundTasksUrl
      key: internalurls__orderingbackground__hc
    - name: LocationsUrl
      key: internalurls__locations__hc
    - name: MarketingUrl
      key: internalurls__marketing__hc
    - name: IdentityUrlHC
      key: internalurls__identity__hc      
    - name: mvc
      key: internalurls__mvc__hc
    - name: spa
      key: internalurls__spa__hc
    - name: PaymentUrl
      key: internalurls__payment__hc
      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: OrchestratorType
      value: 'K8S'
