replicaCount: 1

image:
  repository: microsoft/mssql-server-linux
  tag: 2017-CU7
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1433


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
