version: '3.4'

# The OpenTelemetry docker-compose file is used to configure OpenTelemetry for the services
#
# You need to start it with the following CLI command:
# docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.opentelemetry.zipkin.yml up

services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  identity-api:
    environment:
      - OTEL_USE_EXPORTER=zipkin
      - OTEL_EXPORTER_TOOL_ENDPOINT=${OTEL_EXPORTER_TOOL_ENDPOINT:-http://zipkin:9411/api/v2/spans}
          
  basket-api:
    environment:
      - OTEL_USE_EXPORTER=zipkin
      - OTEL_EXPORTER_TOOL_ENDPOINT=${OTEL_EXPORTER_TOOL_ENDPOINT:-http://zipkin:9411/api/v2/spans}
  
  catalog-api:
    environment:
      - OTEL_USE_EXPORTER=zipkin
      - OTEL_EXPORTER_TOOL_ENDPOINT=${OTEL_EXPORTER_TOOL_ENDPOINT:-http://zipkin:9411/api/v2/spans}
  
  ordering-api:
    environment:
      - OTEL_USE_EXPORTER=zipkin
      - OTEL_EXPORTER_TOOL_ENDPOINT=${OTEL_EXPORTER_TOOL_ENDPOINT:-http://zipkin:9411/api/v2/spans}
  
  payment-api:
    environment:
      - OTEL_USE_EXPORTER=zipkin
      - OTEL_EXPORTER_TOOL_ENDPOINT=${OTEL_EXPORTER_TOOL_ENDPOINT:-http://zipkin:9411/api/v2/spans}
  
  webhooks-api:
    environment:
      - OTEL_USE_EXPORTER=zipkin
      - OTEL_EXPORTER_TOOL_ENDPOINT=${OTEL_EXPORTER_TOOL_ENDPOINT:-http://zipkin:9411/api/v2/spans}
  
  webshoppingagg:
    environment:
      - OTEL_USE_EXPORTER=zipkin
      - OTEL_EXPORTER_TOOL_ENDPOINT=${OTEL_EXPORTER_TOOL_ENDPOINT:-http://zipkin:9411/api/v2/spans}
  
  mobileshoppingagg:
    environment:
      - OTEL_USE_EXPORTER=zipkin
      - OTEL_EXPORTER_TOOL_ENDPOINT=${OTEL_EXPORTER_TOOL_ENDPOINT:-http://zipkin:9411/api/v2/spans}

  webmvc:
    environment:
      - OTEL_USE_EXPORTER=zipkin
      - OTEL_EXPORTER_TOOL_ENDPOINT=${OTEL_EXPORTER_TOOL_ENDPOINT:-http://zipkin:9411/api/v2/spans}
  
  webspa:
    environment:
      - OTEL_USE_EXPORTER=zipkin
      - OTEL_EXPORTER_TOOL_ENDPOINT=${OTEL_EXPORTER_TOOL_ENDPOINT:-http://zipkin:9411/api/v2/spans}
