replicaCount: 1

image:
  repository: mcr.microsoft.com/mssql/server
  tag: 2019-latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1433


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
