kind: Deployment
apiVersion: apps/v1
metadata:
  name: backgroundtasks
  labels:
    app: eshop
    service: backgroundtasks
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backgroundtasks
  template:
    metadata:
      labels:
        app: eshop
        service: backgroundtasks
    spec:
      containers:
        - name: ordering-backgroundtasks
          image: {{ .Values.registry }}/ordering.backgroundtasks:linux-net6-initial
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 80
              path: /liveness
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              port: 80
              path: /hc
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: backgroundtasks-cm
