name: Deploy basket-api

on:

  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'execution name'
        # Default value if no value is explicitly provided
        default: 'Manual End to End Deployment'
        # Input has to be provided for the workflow to run
        required: false
        
  repository_dispatch:
    types:
    - deploy
    
  workflow_run:
    workflows: ["basket-api"]
    branches: [dev]
    types: [completed]

env:
  CHART: basket-api
  NAMESPACE: eshop
  CHART_ROOT: deploy/k8s/helm

jobs:
  deploy-to-k8s:
    #if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    if: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/workflows/composite/deploy-helm
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          resource_group: ${{ secrets.RESOURCE_GROUP }}
          registry_host: ${{ secrets.REGISTRY_HOST }}
          chart: ${{ env.CHART }}
          chart_root: ${{ env.CHART_ROOT }}
          namespace: ${{ env.NAMESPACE }}
