name: webshoppingagg

on:
  workflow_dispatch:
  push:
    branches:
    - dev

    paths:
    - src/ApiGateways/Web.Bff.Shopping/aggregator/**
    - .github/workflows/webshoppingagg.yml
  
  pull_request:
    branches:
    - dev

    paths:
    - src/ApiGateways/Web.Bff.Shopping/aggregator/**
    - .github/workflows/webshoppingagg.yml
env:
  SERVICE: webshoppingagg
  IMAGE: webshoppingagg

jobs:

  BuildContainersForPR_Linux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: ./.github/workflows/composite/build
      with:
        service: ${{ env.SERVICE }}
        registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}

  BuildLinux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: ./.github/workflows/composite/build-push
      with:
        service: ${{ env.SERVICE }}
        registry_host: ${{ secrets.REGISTRY_HOST }}
        registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
        image_name: ${{ env.IMAGE }}
        registry_username: ${{ secrets.USERNAME }}
        registry_password: ${{ secrets.PASSWORD }}