apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: ocelotapigw-mm
  name: ocelotapigw-mm
spec:
  ports:
  - port: 80
  selector:
    app: eshop
    component: apigwmm
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: ocelotapigw-ms
  name: ocelotapigw-ms
spec:
  ports:
  - port: 80
  selector:
    app: eshop
    component: apigwms
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: ocelotapigw-wm
  name: ocelotapigw-wm
spec:
  ports:
  - port: 80
  selector:
    app: eshop
    component: apigwwm
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: ocelotapigw-ws
  name: ocelotapigw-ws
spec:
  ports:
  - port: 80
  selector:
    app: eshop
    component: apigwws
